name: 🚢 Deploy

on:
  push:
    branches:
      - main

jobs:
  john:
    runs-on: ubuntu-latest
    name: 🤓 😎 John
    steps:
      - uses: actions/checkout@v3
      - name: 🚀 Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'packages/john'
